### ISSUE TITLE
Rework download of population data

### ISSUE THREAD

**Issue by KPunktRPunkt** [DLR-SC/memilio#109]
The script to download population data has to be reworked completely. Some parts are just workarounds, due to changes in data.  Note: not all problems might still exist.

Check the following and more

- [ ] Usage of existing functions like loadCsv
- [ ] Check tests
- [ ] Added to setup.py?
- [ ] use pandas functionality for read_age_population 
- [ ] Check depricated url and if needed use new one (at the moment not used)
- [ ] Data splitted by age and gender?

About read_age_population function
- [ ] Add unittests
- [ ] Check usage if migration data
- [ ] Rename column total
- [ ] Remember Bug for migration data that Bevölkerung2 has to be used.
- [ ] Add doxygen like documentation
 
Following data might be interesting:
https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Bevoelkerungsstand/_inhalt.html#sprg233974

https://hub.arcgis.com/search?q=Zensus

https://www.zensus2011.de/DE/Home/Aktuelles/DemografischeGrunddaten.html?nn=3065474
https://www-genesis.destatis.de/genesis/online?operation=abruftabelleBearbeiten&levelindex=1&levelid=1593594767620&auswahloperation=abruftabelleAuspraegungAuswaehlen&auswahlverzeichnis=ordnungsstruktur&auswahlziel=werteabruf&code=12411-0012&auswahltext=&werteabruf=Werteabruf#abreadcrumb
https://www-genesis.destatis.de/genesis/online?operation=previous&levelindex=0&step=0&titel=Statistik+%28Tabellen%29&levelid=1593594738977&acceptscookies=false#abreadcrumb

**Comment by dabele** [comment]
@xsaschako, in case you haven't seen it. also please contact @KPunktRPunkt to clarify any unclear points. maybe create separate issues in case the points above are not resolved by #103
