### ISSUE TITLE
Get estimation of number of hospitalized from pdf

### ISSUE THREAD

**Issue by KPunktRPunkt** [DLR-SC/memilio#110]
We want to have the numbers of hospitalized. There are different possibilities to get it:

- [ ] from RKI Tagesbericht pdf 
- [ ] from monthly-data of RKI. Until lately it was a xlsx file now it seems to be on github as well: https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

**Comment by mknaranja** [comment]
Data is now also available at https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland

**Comment by dabele** [comment]
Duplicate of #128
