### ISSUE TITLE
unqualified try-except in getSimulationData

### ISSUE THREAD

**Issue by dabele** [DLR-SC/memilio#130]
the `get_simulation_data` function in the epidata python package uses unqualified try-except, e.g.:
```
try:
  getDIVIData.get_divi_data(**arg_dict_divi)
except:
  print_error('Divi')
```
this catches and reports all exceptions, including system messages like keyboard interrupts (Ctrl-C). The except clauses should be qualified to only catch errors.

The same problem in some other files as well, grep for `except:`.

**Comment by annette-lutz** [comment]
This issue is resolved by the merge above.
