### ISSUE TITLE
progress dispay for python data download and processing

### ISSUE THREAD

**Issue by dabele** [DLR-SC/memilio#131]
Users of epidata python package don't get any feedback about what's happening. There should be some logging and progress display.

Text to notify of processing steps if necessary, not too detailed, so there is no spam and no information that users can't understand anyway.

Percentages or data amounts would be best for progress display, some other busy indicator otherwise. right now it just looks like it's stuck and users have no idea why or what they could do to speed it up.

**Comment by dabele** [comment]
also I think a good first issue @annette-lutz @mknaranja

**Comment by reneSchm** [comment]
I made a class ProgressIndicator in branch 131-progress-indicator that can print simple animations (spinner or dots) or percentages (with bars). For example, we can simply do
```
from memilio.ProgressIndicator import ProgressIndicator
with ProgressIndicator.Spinner():
    run_long_task(...)
```
and a spinner will run next to the output for the duration of the function.

Percentages can be used similarly, but I have not found a simple way to get them from pandas or to compute them :/

**Comment by reneSchm** [comment]
Yes, since we still do not have a (usable) function to replace pd.read_csv(url, ...), that can output its progress.
I have a prototype that can download URLs, but a proper replacement should also be able to open local files, which I didn't manage to do yet.
