### ISSUE TITLE
Implement Integro-differential equation model

### ISSUE THREAD

**Issue by lenaploetzke** [DLR-SC/memilio#132]
In addition to ODE and ABM models, it would be useful to implement models based on integro-differential equations.

ODE-based models can be seen as a special case of IDE-based models. As a consequence, in some simulations in the literature with IDE and ODE models, a better approximation of the real infection dynamics by the IDE model was found.

For further information see e.g. _"DOI:10.13140/RG.2.2.10845.44000"_.

**Comment by mknaranja** [comment]
Closed as duplicate of #51
