### ISSUE TITLE
Fix Function create_intervals_mapping in GetVaccinationData 

### ISSUE THREAD

**Issue by xsaschako** [DLR-SC/memilio#139]
The function calculates mappings from multiple intervals to different multiple intervals.
This works for the case that 1 interval is mapped onto two others, but not from 1 to more than 2.
This could be generalized.

For example:
`[0, 10, 100]`
onto
`[0, 50, 60, 70, 100]`
results in
```
0:[[1, 0]]
1:[[0.5555555555555556, 0], [0.6666666666666667, 1], [0.7777777777777779, 2], [0.2222222222222221, 3]]
```
but should be

```
0:[[1, 0]]
1:[[0.444, 0], [0.111, 1], [0.111, 2], [0.333, 3]]
```

**Comment by dabele** [comment]
can you add a bit more detail, e.g. give an example for a mapping that doesn't work
