### ISSUE TITLE
Switch to github for getRKIData

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#146]
Since RKI now also provides infection data on github, after a verification step, we should probably switch the download address to github. There we also find data frames for past dates.

**Comment by mknaranja** [comment]
This would be a good first issue @annette-lutz

**Comment by dabele** [comment]
example link: 
https://github.com/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland
https://media.githubusercontent.com/media/robert-koch-institut/SARS-CoV-2_Infektionen_in_Deutschland/master/Archiv/2021-12-07_Deutschland_SarsCov2_Infektionen.csv

the  files have the same format as the old sources, except some columns are missing:
- Bundesland ID: can be derived from Landkreis Id
- Bundesland und Landkreis name: not needed, just blow up data size. Can be put in a separate file if needed
- Altergruppe2: alternative grouping, obsolete.
- Datenstand: only needed for verification, if at all. for rki data it seems to be always the day of the upload that is also included in the file name

**Comment by dabele** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MemilioESID-614316fd7ccb67000fcf886b/issues/DLR-SC/memilio/146?planning-poker) with ZenHub @mknaranja

**Comment by annette-lutz** [comment]
Should the data only be downloaded from github or should the script try to dowload the data from the old sources we are using at the moment in case that the dowload from github fails?

**Comment by mknaranja** [comment]
I think an alternative source would be a good option that prevents the download from failing if one server is temporary offline at CI run for instance...
