### ISSUE TITLE
Update python epidata readme

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#147]
The epidata readme https://github.com/DLR-SC/memilio/tree/main/pycode/memilio-epidata and https://github.com/DLR-SC/memilio/tree/main/pycode/memilio-epidata/memilio/epidata is out of date and should be updated.

We should think of merging these two sets and removing one of them (maybe the lowest level one)

**Comment by dabele** [comment]
The URLs in the readmes still point to gitlab internal pages (#112)

**Comment by annette-lutz** [comment]
In the section about "Running the scripts" in both readmes the readme of the folder above is referenced for the entry points.
But the readme in pycode defining the entry points getrkidata, getpopulationdata, getjhdata, getdividata, getsimdata, cleandata, getcommutermigration is deleted. Should this information be again integrated in the current readmes or are those entry points deprecated and the reference to them in the readmes should be deleted?

**Comment by annette-lutz** [comment]
Is there a pylint report for the main branch? The link in the epidata README.rst for the pylint report seems to be deprecated.
