### ISSUE TITLE
Change numpy version

### ISSUE THREAD

**Issue by annette-lutz** [DLR-SC/memilio#170]
Upgrade numpy to version 1.21 or later since the currently used numpy version 19.4.1 raises a security warning.

**Comment by annette-lutz** [comment]
Locally I tested the new numpy version 1.22.1 with python 3.8.10 which is compatible. But the CI works with python 3.6.15 which is only compatible up to numpy version 1.19.5, see https://numpy.org/doc/stable/release/1.20.0-notes.html. So, to switch to a higher numpy version which does not raise a security warning the python version used needs to be changed too.

**Comment by dabele** [comment]
1. Does python 3.6 work with numpy > 1.20, despite being officially unsupported?
2. I'm fine with bumping python versions. It makes sense to only officially support (i.e. test) python versions that are also officially supported by our dependencies. Lower versions may still work anyway, but no guarantees. Python 3.6 is itself no longer supported by its maintainers. CI uses Py 3.6, 3.7, 3.8, so I would say drop 3.6, add 3.9, maybe 3.10. Maybe we don't need to test all versions in between, for C++ compilers we only test a minimum and a latest version, e.g. clang 6 and clang 12. For python, that would mean 3.7 and 3.10. Reduces our CI footprint a little bit.
