### ISSUE TITLE
Extend writeDataFrame to csv/txt format and improve loadCsv

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#190]
getDataIntoPandasDataFrame.py writeDataFrame cannot export to csv format so far. This should be extended.

Also loadCsv should be extended to allow for handing over separator item (e.g., sep=' ') and header (e.g., header=None)

If this is done, transformMobilityData.py should use these extended functions.

See also _Originally posted by @patricklnz in https://github.com/DLR-SC/memilio/pull/180#discussion_r792730083_

**Comment by patricklnz** [comment]
Also cleanData can't delete csv/txt format. This functionallity should be added when write_dataframe is able to export to csv format. Since those files are written in the 'mobility' directory instead of 'pydata' directory, cleanData can be split by cleanPydata and cleanMobility.

**Comment by patricklnz** [comment]
The extended write_dataframe function should also be used in getCommuterMobility.py.
