### ISSUE TITLE
Migrate Wiki from Gitlab to Github

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/memilio#2]
There are quite a few links in the README *(and the PR template too)* referring to the Gitlab Wiki. We should consider migrating *(and updating?)* the Wiki as well.

In general all README files need cleaning up. There are also a few now dead links to our Gitlab CI artifacts eg in pycode/Readme.rst

**Comment by xsaschako** [comment]
@mknaranja can this be closed? I think so

**Comment by mknaranja** [comment]
Yes. Well recognized. Thanks.
