### ISSUE TITLE
Bug when downloading a excel in getTestingData

### ISSUE THREAD

**Issue by xsaschako** [DLR-SC/memilio#201]
Line 67 in getTestingData:

`df_test[1] = pd.read_excel(df, sheet_name=sheet_names[3], header=[4],dtype={'Anteil positiv': float})`

The error says

Exception has occurred: ValueError
Passed header = 4 but only 2 lines in file

This is discussed in https://github.com/pandas-dev/pandas/issues/38956.

Anette also reproduced that error.

**Comment by annette-lutz** [comment]
This bug is dependend on the pandas version used. It is a bug in pandas that is resolved in pandas version 1.2.2. In #221 this requirement is added to the setup.py.
