### ISSUE TITLE
Add option to avoid output of single run results

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#223]
If a user runs a lot of ensemble runs are done, the output of the single run results which blow up the needed disk space might not be wanted and only output of percentiles is seeked. We should implement an option to avoid outputting data for every single run.

Another interesting option would be to provide the user an estimate of the used disk space.

**Comment by xsaschako** [comment]
@mknaranja can you add lables to this and add this to their respective projects?
