### ISSUE TITLE
Transformation of NPI data and preliminary analysis

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#231]
The https://www.corona-datenplattform.de/ provides finely granulated information on non-pharmaceutical interventions (NPIs) against Sars-CoV-2 on county scale. This information is extracted from official political publications and NPIs are mentioned when they were considered for implementation. However, for incidence-dependent NPIs a combination with incidence data has to done to get to know when which NPIs were active (and not only mentioned in the regulations).

In a first step, this information has to be brought in a pandas data frame as our other data. After combination with incidence data, clustering may be needed to cluster interventions that are highly correlated with respect to the dates when they were active.

**Comment by mknaranja** [comment]
In favor of a well described epic, this one should be closed and #412 #413 #414 should be mentioned in the new epic.

**Comment by mknaranja** [comment]
Clustering now moved to #444

**Comment by patricklnz** [comment]
Tests added in #539
