### ISSUE TITLE
SEH exception in dynamicnpis unittests

### ISSUE THREAD

**Issue by dabele** [DLR-SC/memilio#24]
Unittests for dynamic NPIs crash with an Unknown SEH exception, code 0x00000005. I think it happens only in msvc debug builds.

**Comment by joergbrech** [comment]
We should probably have a debug build in our CI

https://github.com/DLR-SC/memilio/blob/c0328b29636034992cbe46652e612a50b2affd54/.github/workflows/main.yml#L68
