### ISSUE TITLE
Run more build and test variants in CI

### ISSUE THREAD

**Issue by dabele** [DLR-SC/memilio#29]
Currently we build and test two variants in CI:
- GCC debug
- MSVC release

Recent issues have shown (again) that we should probably extend this. Possibilities:
- both debug and release versions for all compilers
- add clang as a compiler since it sometimes has different warnings and assertions
- different compiler versions
- sanitizers: address, thread, UB
- ???

Some of these tests should probably only run nightly or on pull requests, not on every push.

@DLR-SC/hpc-against-corona comments are welcome

**Comment by dabele** [comment]
a moderate extension:
- for every push: gcc, clang, msvc debug builds for one compiler version, sanitizers with small runtime overhead
- for pull requests: + release builds
- nightly:  + different versions (maybe not MSVC depending on the effort), + all sanitizers

**Comment by mknaranja** [comment]
yes, I completely agree. 

- We should run release and debug for all compilers
- we should add clang
- we should at least use two versions for each compiler (an older and a newer one: whatever "old" and "new" means exactly ;-) so like gcc7 and gcc10...)


regarding the extension: also yes :)
