### ISSUE TITLE
test_epidata_geoModificationGermany fails because of different dtypes on windows

### ISSUE THREAD

**Issue by HenrZu** [DLR-SC/memilio#320]
When running the unittests in `test_epidata_geoModificationGermany.py`, the test fails because of different dtypes in the column county_ids in line 549.

The Error code is
```
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="ID_County") 
Attribute "dtype" are different
[left]:  int32
[right]: int64
```

The error occurs in the `geoModificationGermany.py` file (line 561)  when the `merge_df_counties` function is called.
This is because the `separated_ids` input parameter is an Int32 variable.
The initialization takes place in the function call with [16063, 16056]. So a list of integer values.

Surprisingly, the error only appears on Windows.

**Comment by mknaranja** [comment]
@patricklnz We should rather change merge_df_counties. The change in the test in #191 is rather a workaround to me.
