### ISSUE TITLE
m_school_holiday_damping not set when loading graph

### ISSUE THREAD

**Issue by reneSchm** [DLR-SC/memilio#394]
**Describe the bug**
In short: m_school_holiday_damping has different values in Save and Load mode.

In the paper_202011 simulation, the simulated graph can either be saved (i.e. newly created, then saved), or loaded from a previous save. [Currently](https://github.com/DLR-SC/memilio/tree/b96307be613a0def9d735fba7124929246b17f74), when saving the graph the variable UncertainContactMatrix::m_school_holiday_damping (see uncertain_matrix.h) of type DampingSampling is set via [paper_202011.cpp:411](https://github.com/DLR-SC/memilio/blob/b96307be613a0def9d735fba7124929246b17f74/cpp/simulations/paper_202011.cpp#L411) (the end of set_npis(...)).
However, when loading a graph this value is not recovered, i.e. m_school_holiday_damping is default initialized to 0 and without Distribution.

**To Reproduce**
1. Go to 'cpp/'
2. Insert a debug output, e.g. `std::cout << serialize_json(m_school_holiday_damping).value() << "\n";` above [uncertain_matrix.cpp:74](https://github.com/DLR-SC/memilio/blob/b96307be613a0def9d735fba7124929246b17f74/cpp/memilio/epidemiology/uncertain_matrix.cpp#L74) . Consider setting num_runs=1 and num_days_sim=1 in paper_202011.cpp for faster results.
3. Build software via 'cmake --build build'
4. Execute program './simulations/paper_202011 data/ save_dir/ result_dir/' (Save mode)
5. Execute program './simulations/paper_202011 save_dir/ result_dir/' (Load mode)
6. See error

**Expected behavior**
m_school_holiday_damping should have the same value in both Save and Load mode.

**Screenshots**
Debug output on Save:
```
{
        "GroupWeights" :
        {
                "Columns" : 1,
                "Elements" :
                [
                        1,
                        1,
                        1,
                        1,
                        1,
                        1
                ],
                "Rows" : 6
        },
        "Level" : 3,
        "MatrixIndices" :
        [
                1
        ],
        "Time" : 0,
        "Type" : 1,
        "Value" :
        {
                "Distribution" :
                {
                        "LowerBound" : 1,
                        "PredefinedSamples" : [],
                        "Type" : "Uniform",
                        "UpperBound" : 1
                },
                "Value" : 1
        }
}
```
Debug output on Load:
```
{
        "GroupWeights" :
        {
                "Columns" : 1,
                "Elements" :
                [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                ],
                "Rows" : 6
        },
        "Level" : 0,
        "MatrixIndices" : [],
        "Time" : 0,
        "Type" : 0,
        "Value" :
        {
                "Value" : 0
        }
}
```
Note the different Values and the missing "Distribution" object.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Compiler: gcc 9.4
 - Used libraries HDF5 1.10.7, JsonCpp 1.7.4

**Additional context**
My guess is that this missing initialization is caused by UncertainContactMatrix::(de)serialize not handling m_school_holiday_damping, or maybe (a part of) set_npis(...) should be called after loading?

**Labels**
loc::backend model::ode

**Comment by mknaranja** [comment]
@jubicker Could you have a look at this?
