### ISSUE TITLE
Reduce number of warnings in C++ build process

### ISSUE THREAD

**Issue by mknaranja** [DLR-SC/memilio#439]
In the C++ build process, we have a lot/a certain number of warnings. Some come from third party libraries. We should have a look at these and address as many as possible as this makes the build process look problematic (although it isnt).

**Comment by xsaschako** [comment]
When i updated the third party libraries for the m1 the build process hat no errors when upgrading spdlog and jsoncpp to the newest versions.

**Comment by mknaranja** [comment]
Unfortunately, this still needs some work: https://github.com/DLR-SC/memilio/actions/runs/3639268254/jobs/6142448026

**Comment by jubicker** [comment]
This issue has meanwhile been solved.
