### ISSUE TITLE
Replace all occurances of "epidemiology" with "memilio"

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/memilio#5]
We should scan all references (documentation, directory names, cmake targets...) for "epidemiology" and consider renaming them to "memilio".

This is easily `sed`'d, but it will create a whole bunch of merge conflicts.

**Comment by dabele** [comment]
most occurences have been replaced in #99 and #66, remaining references are all in 'pycode/memilio-epidata/README', see #147 and #112
