### ISSUE TITLE
Improve code coverage for python scripts

### ISSUE THREAD

**Issue by jubicker** [DLR-SC/memilio#518]
We should improve the code coverage for the epidata python scripts. Some scripts are not testet at all.

![image](https://user-images.githubusercontent.com/113909589/209083997-ee53c2d8-d016-40ba-a2b9-248f6b9143cf.png)

**Comment by patricklnz** [comment]
Some unittests are currently skipped for Commuter Mobility and getVaccinationData (See Issue #310). The coverage of getCommuterMobility.py will go up when Pull request #230 is merged as they're unskipped. For getTestingData there is already an Issue #192.
