### ISSUE TITLE
Correct Python path to compute coverage

### ISSUE THREAD

**Issue by patricklnz** [DLR-SC/memilio#545]
test-py-epidata fails because thecoverage module can't find our epidata package  with the given path.
`/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/coverage/inorout.py:507: CoverageWarning: Module /opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/memilio/epidata was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/coverage/control.py:838: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
No data to report.`

**Comment by patricklnz** [comment]
It would be good if the path is not python version specific, so it doesn't have to be corrected whenever the used version changes.

**Comment by mknaranja** [comment]
Please make it a new issue @patricklnz
