### ISSUE TITLE
Separate the initialization of Person with TimeSeries object in Location

### ISSUE THREAD

**Issue by khoanguyen-dev** [DLR-SC/memilio#551]
In order to start any simulation, the Simulation object then has the responsibility to initialise all time-dependent objects. Currently, we use the TimeSeries (m_subpopulations) as a container to store the population and there is no meaningful time value to assign to the initial state. The m_subpopulations starts at 0 and change it if a simulation is created to the initial time.

It would be a good idea that persons should be at no location initially and only be assigned to a current location at initialisation of the simulation (except for tests maybe). Potentially, a vector of current persons saved in the location to replace the initialization of subpopulation in the location.

**Comment by DavidKerkmann** [comment]
Please confirm that this has been resolved by #327 .

**Comment by khoanguyen-dev** [comment]
Yes! It should be solved now.
