### ISSUE TITLE
[Enhancement] [Discussion] improvements for the new issue templates

### ISSUE THREAD

**Issue by reneSchm** [DLR-SC/memilio#599]
### Motivation / Current Behaviour

Some ideas/improvements for the new issue templates.

### Enhancement description

Improvements for the [Bug] issue template:
- add an option for "CI" or "Github Actions" to the Verions drop down
- make the "relevant information" section a text field instead of code
  - maybe add an option/toggle for text/code?

Related discussion topics:
- add a location for tests/CI? (e.g. loc::tests)
- add a project for this kind of discussion? (e.g. memilio-github or memilio-meta)
- fix naming of projects (we have a wild mix of ':', ' ' and '-' as seperators in different projects)

### Additional context

(this text tests for another code block. If "for" is red, add "make this a text block" to the enhancements above)

### Checklist

- [x] Attached labels, especially loc:: or model:: labels.
- [x] Linked to project

**Comment by xsaschako** [comment]
> add an option for "CI" or "Github Actions" to the Verions drop down
Done
>make the "relevant information" section a text field instead of code
It is already

>add a location for tests/CI? (e.g. loc::tests)
>add a project for this kind of discussion? (e.g. memilio-github or memilio-meta)
Martin and I discussed this. We opted for a simple tag, namely loc::infrastructure. Projects would be overkill, and I think this is an easy-to-use implementation for managing these tasks.

>fix naming of projects (we have a wild mix of ':', ' ' and '-' as seperators in different projects)
Yeah, fixed that.
