### ISSUE TITLE
Upgrade to Python 11

### ISSUE THREAD

**Issue by xsaschako** [DLR-SC/memilio#626]
### Motivation / Current Behaviour

Python says version 11 is 10-60% faster, we should take that

### Enhancement description

- [x] Test if python 11 runs our programm
- [x] quick test if 10-60% performance increase is really achieve
- [ ] fix conflicts

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by patricklnz** [comment]
Epidata unittests and download files run without any warnings or errors. In terms of performance, I didn't notice a huge difference. I would say 15% increase max but I don't have data on that.

**Comment by patricklnz** [comment]
For using python 11 we need to upgrade [pybind11](https://pybind11.readthedocs.io/en/latest/changelog.html#version-2-10-1-oct-31-2022) >= 2.10.1 (currently 2.5)
