### ISSUE TITLE
Wrong call of function gd.get_file in getPopulationData.py

### ISSUE THREAD

**Issue by jubicker** [DLR-SC/memilio#655]
### Bug description

When executing getPopulationData.py there is the possibility of downloading the 'Bevölkerungsfortschreibung' automatically or manually downloading the excel file 12411-02-03-4.xlsx and using this. When using the excel file, the variable new_data_avail is set true and gd.get_file is called with the arguments apiUrl='' and extension='.xlsx'. This causes an error, bacause the function get_file has no arguments apiUrl and extension.

### Version

Linux

### To reproduce

1. Install memilio-epidata package
2. Download 12411-02-03-4.xlsx like described in line 208ff in getPopulationData.py and save it in data/pydata/Germany
3. execute getPopulationData.py

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by patricklnz** [comment]
Closed by #661
