### ISSUE TITLE
libmagic cannot be found in memilio-epidata

### ISSUE THREAD

**Issue by jubicker** [DLR-SC/memilio#679]
### Bug description

When installing memilio-epidata, libmagic is installed with the newest version. This version causes the error 
`ImportError: failed to find libmagic.  Check your installation` when wanting to use libmagic.
It works with version 0.4.14.

### Version

Windows

### To reproduce

Install memilio-epidata via pip install

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by mknaranja** [comment]
@HenrZu @patricklnz I'd like to reopen this issue as I still have the problem right now and I used the current main.

**Comment by mknaranja** [comment]
Update: No problem on Ubuntu though.

**Comment by HenrZu** [comment]
I have just tried to reproduce the error in my windows. 
```
python --version 
>>Python 3.10.6  
```        
However, it works for me and I don't get an error.
```
python-magic                 0.4.13
python-magic-bin             0.4.13
```

Can you, @patricklnz, reproduce this?

**Comment by patricklnz** [comment]
Hey @HenrZu, I am currently working on this. I can reproduce the error by uninstalling the package and then using the setup.py function. However, I think I found a solution and will open a Pull Request this week.
