### ISSUE TITLE
Exposed people infect others in ABM

### ISSUE THREAD

**Issue by jubicker** [DLR-SC/memilio#681]
### Motivation / Current Behaviour

In the ABM exposed people are infective and are able to infect others.

### Enhancement description

Should exposed infect others?

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by mknaranja** [comment]
I just discussed with @DavidKerkmann and here are some thoughts:

- As discussed last week, the parameters `SusceptibleToExposedByInfectedNoSymptoms` and `SusceptibleToExposedByInfectedSymptoms` are leftovers of the former transmission modeling were exposed could not infect others. So these parameters should be removed first.
- Now, the `ViralLoad` is a continuous variable from transmission on and theoretically exposed people can infect others. If this probability is *very low*, this is probably more realistic than modeling in ODE where the probability to transmit is exactly *zero* for days. Here, we could mabybe tackle this issue by defining a threshold value for the transmission based on the viral load. If the viral load increases very slowly at the beginning this could be a) realistic and b) in accordance to other models (e.g. ODEs)
- We have a strong inconsistency at the moment: The `Exposed` state (and others) does not mean anything/much as the corresponding parameter is not coupled/dependent to the viral load or the ability to infect. This should be corrected soon.

There are also some issues that @xsaschako could take over, to make our model reusable in a meaningful way quickly.

**Comment by mknaranja** [comment]
I forgot:
- The viral_load and infectivity function should be documented in more detail. It should minimally be noted that the viral load is in log scale and it should be mentioned more directly how the exponential function comes into play.

**Comment by xsaschako** [comment]
Thank you, @mknaranja. Please take a brief look at the action items here. I will propose code soon, as this will probably be tiny.

- [ ] Document viral_load and infectivity function in more detail.
- [ ] Delete  the parameters SusceptibleToExposedByInfectedNoSymptoms and SusceptibleToExposedByInfectedSymptoms and any leftovers from the previous transition model.

The next one is open to discussion, but maybe a coupling of being exposed with the viral load
- [ ] Define the viral load threshold.

**Comment by jubicker** [comment]
In the interaction method in location.cpp we calculate the individual transmission probability using 
`dt.days() / days(1).days()`
As dt.days() already transforms dt to days, the denominator can be removed.

**Comment by DavidKerkmann** [comment]
Let me sum up the problem once more quickly:
In the ODE, we **do not** have a separation between infectiousness and symptoms. Both of these are coupled in the compartment definitions and transitions.
In the ABM, we now **do** have this separation. The newly implemented viral load and infectiousness model give us some much needed utility for the ABM. The model for the symptoms, however, has in a way been "copied" from the ODE compartments, which fulfils the purpose of comparing between the models but still inherits the infectiousness parts.
Thus, a clear cut between the two should be aimed for in the ABM.

After some consideration, I propose the following:
We remove the InfectionStates `Exposed` and `Recovered` from the ABM. Removing `Recovered` was already planned, as there is no difference to `Susceptible` if we only look at the symptoms. Removing `Exposed` leads to every newly infected person moving to `InfectedNoSymptoms` immediately and they do have a chance to infect people as of the current infectivity model.
Adding a threshold for being able to infect others is an option, but I commend that this should be handled in addition to this change to account for the needs of comparison to other models or the needs of any external party. In this regard, I suggest moving the infectivity function to the parameters, so it can be set individually for any virus (type).
Going further, an idea would be to rename `InfectionState` to `SymptomaticState` or similar, and considering renaming of some of the attributes too, as there is no complete 1:1 relation to the InfectionStates of the ODE anyway. For example, we could have `NoSymptoms, InfectedNoSymptoms, InfectedSymptoms, InfectedSevere, InfectedCritical, Dead`. Looking at this, we can even combine the first two states, as we would only track symptoms with this.

A transformation between the models would need to take both ViralLoad and SymptomaticState into account, but I reckon that this is not a problem. An `Exposed` person could be inferred through the `(Infected)NoSymptoms` state and a low viral load (below a threshold (which might also be used in the infectiousness function)).

Please comment your thoughts on this.

**Comment by xsaschako** [comment]
Thank you @DavidKerkmann. I support your suggestions, as these make this way more clear.

As discussed we will do the following:

- [ ] We will fix in this issue the problem that exposed people infect others and the two minoor issues that are mentioned above
- [ ] open another  issue to adress the symptomatic states

**Comment by mknaranja** [comment]
> Let me sum up the problem once more quickly: In the ODE, we **do not** have a separation between infectiousness and symptoms. Both of these are coupled in the compartment definitions and transitions. In the ABM, we now **do** have this separation. The newly implemented viral load and infectiousness model give us some much needed utility for the ABM. The model for the symptoms, however, has in a way been "copied" from the ODE compartments, which fulfils the purpose of comparing between the models but still inherits the infectiousness parts. Thus, a clear cut between the two should be aimed for in the ABM.
> 
> After some consideration, I propose the following: We remove the InfectionStates `Exposed` and `Recovered` from the ABM. Removing `Recovered` was already planned, as there is no difference to `Susceptible` if we only look at the symptoms. Removing `Exposed` leads to every newly infected person moving to `InfectedNoSymptoms` immediately and they do have a chance to infect people as of the current infectivity model. Adding a threshold for being able to infect others is an option, but I commend that this should be handled in addition to this change to account for the needs of comparison to other models or the needs of any external party. In this regard, I suggest moving the infectivity function to the parameters, so it can be set individually for any virus (type). Going further, an idea would be to rename `InfectionState` to `SymptomaticState` or similar, and considering renaming of some of the attributes too, as there is no complete 1:1 relation to the InfectionStates of the ODE anyway. For example, we could have `NoSymptoms, InfectedNoSymptoms, InfectedSymptoms, InfectedSevere, InfectedCritical, Dead`. Looking at this, we can even combine the first two states, as we would only track symptoms with this.
> 
> A transformation between the models would need to take both ViralLoad and SymptomaticState into account, but I reckon that this is not a problem. An `Exposed` person could be inferred through the `(Infected)NoSymptoms` state and a low viral load (below a threshold (which might also be used in the infectiousness function)).
> 
> Please comment your thoughts on this.

@DavidKerkmann Thanks for this detailed summary. I agree to most of your points, however, I am hesitant / would not like to deviate too much from other models naming. Still I understand it could make sense here. Please let us discuss this if you really want to rename things.
