### ISSUE TITLE
Separate python bindings from data handling library

### ISSUE THREAD

**Issue by dabele** [DLR-SC/memilio#69]
The data handling library does not really depend on the python bindings. But they can only be installed and tested together. This causes multiple issues:
- CI workflow is slower than necessary, since the long jobs for download-data and py-test can only start after py-build
- Pure C++ users still need to build the python bindings to download data.

The libraries should be separated into independet packages.

**Comment by dabele** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MemilioESID-614316fd7ccb67000fcf886b/issues/DLR-SC/memilio/69?planning-poker) with ZenHub @mknaranja @joergbrech

**Comment by dabele** [comment]
@mknaranja @joergbrech I know you probably can't really know how long this will take, but I wanted to try the planning poker feature

**Comment by joergbrech** [comment]
@dabele, I voted, but my vote seems a bit arbitrary to me. So I wonder how we should go about this in general. I guess we have the following two options:

 - We could not talk about how we interpret the story points in terms of workload and see if we reach an implicit consensus over time with experience.
 - We could agree on an "anchor", e.g. "An issue with 40 story points is an issue that will require one person to work full time on it during one sprint".

**Comment by mknaranja** [comment]
Yes, we have to agree on something and regarding @dabele estimate in #74 I think we still have different opinions on what the maximum (40) means. The question is if the maximum is adapted to a sprint or if 40 can even be more than a sprint.

**Comment by dabele** [comment]
opened #76 to continue this discussion.
