### ISSUE TITLE
Expand Model for Vaccination Paper

### ISSUE THREAD

**Issue by WadimKoslow** [DLR-SC/memilio#74]
Several new compartments need to be added to our current secir Model in order to simulate effects of vaccinations. Furthermore Commuter testing, which was introduced in our second paper needs to be implemented.

**Comment by mknaranja** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MemilioESID-614316fd7ccb67000fcf886b/issues/DLR-SC/memilio/74?planning-poker) with ZenHub @dabele

**Comment by dabele** [comment]
"Unable to vote [...] when a final estimate is set." And I can't take the estimate off anymore. I set it to something more realistic (I think, but @WadimKoslow should know more) for now.
