### ISSUE TITLE
pages job is broken due to new coverage generation

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/memilio#82]
Since the pages job is only executed on main, I missed updating it as part of #81, my bad.

**Comment by dabele** [comment]
would there be a way to do a trial run during pull requests? But I guess it's not that critical, since it doesn't stop anyone from working with the software, just the page may be out of date for at most a few days, right?

**Comment by joergbrech** [comment]
> would there be a way to do a trial run during pull requests? But I guess it's not that critical, since it doesn't stop anyone from working with the software, just the page may be out of date for at most a few days, right?

I still think this is a good idea. Currently it is not critical, but as soon as we brush up our (doxygen) documentation, it would be nice to check if everything works before the merge so that we always have an up-to-date documentation. We could generate the pages with every non-minimal CI job (`on pull_request`) and only publish to gh-pages on main.
